---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# sostieteidentaulukointityylit

<!-- badges: start -->
<!-- badges: end -->
Paketti tekee tavallisimmista tilastoanalyysien tulosobjekteista Helsingin yliopiston sosiaalitieteiden koulutusohjelmien mukaisia tulostaulukoita. Tyyli noudattelee pääpiirteissään APA 7th -ohjeita, muutamia suomen kieleen liittyviä poikkeuksia lukuunottamatta.

Versio 0.1, testaillaan. Tällä hetkellä paketissa on seuraavat funktiot:

* tee_faktorianalyysitaulukko() - psych-paketin faktorianalyyseille

* tee_korrelaatiotaulukko() - tee APA-käytännön mukainen taulukko korrelaatiomatriisista

* tee_korrelaatiotaulukko_kuvailevin_tunnusluvuin() - tee APA-käytännön mukainen taulukko korrelaatiomatriisista siten, että jokaisen muuttujan havaintojen määrä, keskiarvo ja keskihajonta ovat myös taulukossa

* tee_regressiotaulukko() - lm-regressiomalleille

* tee_regressiotaulukko_selitettava_rivina() - lm-regressiomalleille (eri selitettävien yhdistämiseen samaan taulukkoon)

* tee_r2_yhteenveto() - useamman mallin selitysosuuksien tilastollinen vertailu

* tee_log_regressiotaulukko - tee logistisen regressioanalyysin taulukko



## asennus

Asenna suorittamalla seuraavat koodi. Jos et ole asentanut devtools-pakettia, asenna se ensin.

``` r
# install.packages("devtools")
devtools::install_github("arhot/sostieteidentaulukointityylit")
```

---
Ylläpito Arho Toikka <arho.toikka@helsinki.fi> 

